@startuml
'https://plantuml.com/class-diagram


class a
class b
class c
class d
1 <|-- a
2 <|-- a
2 <|-- b
1 <|-- b
1 <|-- c
3 <|-- c
1 <|-- d
3 <|-- d
interface 1{
operation1();void
}
interface 2{
operation2();void
operation3();void
}
interface 3{
operation4();void
operation5();void
}
@enduml